package controllers

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"yios/database"
	"yios/models"
	"yios/services"
)

// GetMetrics returns real-time Pods, CPU usage %, Memory footprint, and requests/sec
func GetMetrics(c *gin.Context) {
	id := c.Param("id")
	var d models.Deployment
	if err := database.DB.First(&d, id).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Deployment not found"})
		return
	}

	metrics := services.GetPodMetrics(&d)
	c.JSON(http.StatusOK, gin.H{"metrics": metrics})
}

// GetPodLogs returns live stream or snapshot logs for a deployment pod
func GetPodLogs(c *gin.Context) {
	id := c.Param("id")
	var d models.Deployment
	if err := database.DB.First(&d, id).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Deployment not found"})
		return
	}

	podName := c.Query("podName")
	if podName == "" {
		podName = fmt.Sprintf("%s-pod-1-x89ab", d.Name)
	}

	logs := services.GeneratePodLogs(&d, podName)
	c.JSON(http.StatusOK, gin.H{
		"deploymentId": d.ID,
		"podName":      podName,
		"logs":         logs,
	})
}

// GetManifest returns synthesized Kubernetes Deployment/Service/Ingress/HPA YAML
func GetManifest(c *gin.Context) {
	id := c.Param("id")
	var d models.Deployment
	if err := database.DB.First(&d, id).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Deployment not found"})
		return
	}

	yamlManifest := services.GenerateK8sManifests(&d)
	dockerfile := services.GenerateDockerfile(d.Framework, d.SourceURL)

	c.JSON(http.StatusOK, gin.H{
		"deploymentId": d.ID,
		"name":         d.Name,
		"manifestYaml": yamlManifest,
		"dockerfile":   dockerfile,
	})
}

// ProxyInference Endpoint lets developers trigger AI model inference via the generated public route
func ProxyInference(c *gin.Context) {
	id := c.Param("id")
	var d models.Deployment
	if err := database.DB.First(&d, id).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Deployment not found"})
		return
	}

	c.JSON(http.StatusOK, gin.H{
		"status":        "200 OK",
		"service":       d.Name,
		"framework":     d.Framework,
		"endpoint":      d.PublicEndpoint,
		"activeReplicas": d.Replicas,
		"response": gin.H{
			"model":     d.Name,
			"inference": "Sample AI response generated by Yios Kubernetes Ingress Router",
			"latencyMs": 24.5,
		},
	})
}
